export const DIMENSIONS = [
  {
    id: "dinero-transacciones",
    name: "Dinero y transacciones",
    shortName: "Transacciones",
    pilot: "Piloto A: Bases financieras y transacciones cotidianas",
  },
  {
    id: "presupuesto-planificacion",
    name: "Presupuesto y planificacion",
    shortName: "Planificacion",
    pilot: "Piloto B: Planificacion, ahorro y decisiones de consumo",
  },
  {
    id: "credito-deuda",
    name: "Credito, deuda y costo del dinero",
    shortName: "Credito y deuda",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "riesgo-digital",
    name: "Riesgo, fraude y decisiones digitales",
    shortName: "Riesgo digital",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "trabajo-empresa",
    name: "Trabajo, empresa e ingresos",
    shortName: "Empresa e ingresos",
    pilot: "Piloto D: Emprendimiento, ingresos y manejo de caja",
  },
  {
    id: "hogar-ciudadania",
    name: "Hogar, ciudadania y responsabilidad economica",
    shortName: "Hogar y ciudadania",
    pilot: "Piloto E: Hogar, ciudadania y responsabilidad economica",
  },
];

export const PILOTS = {
  bases: {
    id: "bases",
    name: "Piloto A: Bases financieras y transacciones cotidianas",
    focus: "Compras, pagos, descuentos, recibos, comprobantes y costo total.",
    duration: "4 a 6 semanas",
  },
  planificacion: {
    id: "planificacion",
    name: "Piloto B: Planificacion, ahorro y decisiones de consumo",
    focus: "Presupuesto, ahorro, priorizacion, manejo de dinero limitado y consumo.",
    duration: "6 semanas",
  },
  creditoRiesgo: {
    id: "creditoRiesgo",
    name: "Piloto C: Credito, deuda y riesgo digital",
    focus: "Costo total, cuotas, compromisos futuros, fraude digital y verificacion.",
    duration: "6 semanas",
  },
  empresa: {
    id: "empresa",
    name: "Piloto D: Emprendimiento, ingresos y manejo de caja",
    focus: "Ingresos, costos, utilidad, caja y emprendimiento escolar.",
    duration: "4 a 6 semanas",
  },
  hogar: {
    id: "hogar",
    name: "Piloto E: Hogar, ciudadania y responsabilidad economica",
    focus: "Presupuesto familiar, consumo responsable, decisiones compartidas y prioridades.",
    duration: "4 a 6 semanas",
  },
};

export const QUESTIONS = [
  {
    id: 1,
    dimension: "dinero-transacciones",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Basica",
    prompt:
      "En la cafeteria del colegio, Valeria compra un sandwich de $8.000 y un jugo de $4.500. Paga con un billete de $20.000. ¿Cuanto dinero deben devolverle?",
    options: ["$7.000", "$7.500", "$8.500", "$12.500"],
    answer: 1,
    rationale: "$8.000 + $4.500 = $12.500. $20.000 - $12.500 = $7.500.",
    visual: {
      type: "receipt",
      title: "Cafeteria escolar",
      rows: [
        ["Sandwich", "$8.000"],
        ["Jugo", "$4.500"],
        ["Pago recibido", "$20.000"],
        ["Cambio", "?"],
      ],
    },
  },
  {
    id: 2,
    dimension: "dinero-transacciones",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Una camiseta cuesta $80.000 y tiene un descuento del 25%. ¿Cuanto se debe pagar por la camiseta despues del descuento?",
    options: ["$20.000", "$55.000", "$60.000", "$75.000"],
    answer: 2,
    rationale: "El 25% de $80.000 es $20.000. $80.000 - $20.000 = $60.000.",
    visual: {
      type: "receipt",
      title: "Compra con descuento",
      rows: [
        ["Precio inicial", "$80.000"],
        ["Descuento", "25%"],
        ["Valor a pagar", "?"],
      ],
    },
  },
  {
    id: 3,
    dimension: "dinero-transacciones",
    competence: "Identificar informacion financiera",
    type: "Caso situacional",
    difficulty: "Basica",
    prompt:
      "Daniel compra por internet unos tenis de $150.000. Antes de pagar, la pagina le muestra un costo de envio de $12.000. ¿Cual es el costo total de la compra?",
    options: ["$138.000", "$150.000", "$152.000", "$162.000"],
    answer: 3,
    rationale: "$150.000 + $12.000 = $162.000.",
    visual: {
      type: "receipt",
      title: "Compra en linea",
      rows: [
        ["Tenis", "$150.000"],
        ["Envio", "$12.000"],
        ["Total", "?"],
      ],
    },
  },
  {
    id: 4,
    dimension: "dinero-transacciones",
    competence: "Interpretar informacion financiera",
    type: "Interpretacion de recibo",
    difficulty: "Media",
    prompt:
      "Sofia recibe este recibo: cuaderno $9.000, lapices $6.000 y cartulina $3.500. Si pago con $20.000, ¿cual afirmacion es correcta?",
    options: [
      "Le deben devolver $1.500.",
      "Le deben devolver $2.500.",
      "Le faltan $1.500.",
      "Pago exactamente el total.",
    ],
    answer: 0,
    rationale: "$9.000 + $6.000 + $3.500 = $18.500. Le devuelven $1.500.",
    visual: {
      type: "receipt",
      title: "Recibo de papeleria",
      rows: [
        ["Cuaderno", "$9.000"],
        ["Lapices", "$6.000"],
        ["Cartulina", "$3.500"],
        ["Pago", "$20.000"],
      ],
    },
  },
  {
    id: 5,
    dimension: "dinero-transacciones",
    competence: "Evaluar decision financiera",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt:
      "Al pagar en una tienda, a Miguel le dicen que puede recibir el recibo en papel o revisar el comprobante digital. ¿Por que es importante conservar o revisar el comprobante?",
    options: [
      "Porque sirve para decorar el cuaderno.",
      "Porque permite verificar lo que pago y hacer reclamos si hay errores.",
      "Porque siempre permite comprar mas barato.",
      "Porque evita que tenga que pagar impuestos.",
    ],
    answer: 1,
    rationale: "El comprobante permite verificar valores y respaldar reclamos.",
  },
  {
    id: 6,
    dimension: "presupuesto-planificacion",
    competence: "Evaluar prioridades",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Andres recibe $70.000 para la semana. Debe usar $24.000 en transporte, quiere guardar $15.000 para una salida del colegio y piensa comprar audifonos de $45.000. ¿Cual decision muestra mejor planificacion?",
    options: [
      "Comprar los audifonos primero y mirar despues como paga el transporte.",
      "Separar primero transporte y ahorro, y revisar si todavia le alcanza para comprar los audifonos.",
      "Usar todo el dinero en la salida del colegio y pedir prestado para lo demas.",
      "Guardar todo el dinero y no pagar transporte esa semana.",
    ],
    answer: 1,
    rationale: "Prioriza transporte y meta de ahorro antes del gasto opcional.",
    visual: {
      type: "budget",
      title: "Dinero semanal de Andres",
      rows: [
        ["Disponible", "$70.000"],
        ["Transporte", "$24.000"],
        ["Ahorro salida", "$15.000"],
        ["Audifonos", "$45.000"],
      ],
    },
  },
  {
    id: 7,
    dimension: "presupuesto-planificacion",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Mariana quiere ahorrar $120.000 en 6 semanas para una actividad del colegio. ¿Cuanto debe ahorrar cada semana para alcanzar la meta?",
    options: ["$10.000", "$15.000", "$20.000", "$30.000"],
    answer: 2,
    rationale: "$120.000 / 6 = $20.000.",
  },
  {
    id: 8,
    dimension: "presupuesto-planificacion",
    competence: "Evaluar prioridades",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Camila tiene $50.000. Debe pagar $18.000 de transporte y $12.000 de materiales para una clase. Tambien quiere comprar una gorra de $35.000. ¿Que deberia hacer primero?",
    options: [
      "Comprar la gorra porque es lo que mas quiere.",
      "Separar transporte y materiales antes de decidir si compra la gorra.",
      "Gastar todo y pedir prestado para los materiales.",
      "No pagar transporte ni materiales para ahorrar.",
    ],
    answer: 1,
    rationale: "Primero cubre compromisos necesarios y luego revisa gastos opcionales.",
    visual: {
      type: "budget",
      title: "Prioridades de Camila",
      rows: [
        ["Disponible", "$50.000"],
        ["Transporte", "$18.000"],
        ["Materiales", "$12.000"],
        ["Gorra", "$35.000"],
      ],
    },
  },
  {
    id: 9,
    dimension: "presupuesto-planificacion",
    competence: "Evaluar alternativas",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Una familia planeo gastar $300.000 en mercado, pero ese mes tuvo que pagar $80.000 adicionales por un arreglo urgente. ¿Cual seria una decision responsable?",
    options: [
      "Ignorar el gasto urgente y seguir gastando igual.",
      "Revisar el presupuesto y ajustar algunos gastos no necesarios.",
      "Pedir prestado sin saber como pagara.",
      "Dejar de comprar alimentos para cubrir todo el arreglo.",
    ],
    answer: 1,
    rationale: "Un imprevisto requiere ajustar gastos no esenciales sin descuidar necesidades.",
  },
  {
    id: 10,
    dimension: "presupuesto-planificacion",
    competence: "Actitud / habito",
    type: "Actitudinal",
    difficulty: "No calificable",
    attitude: true,
    prompt: "Cuando quiero comprar algo y no me alcanza el dinero, normalmente:",
    options: [
      "Lo compro igual si puedo pedir prestado.",
      "Reviso si puedo esperar, ahorrar o buscar una opcion mas economica.",
      "Le pido dinero a alguien sin pensar mucho.",
      "Uso el dinero que tenia separado para algo importante.",
    ],
    positive: 1,
    rationale: "La opcion B indica mayor tendencia a planificacion.",
  },
  {
    id: 11,
    dimension: "credito-deuda",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Laura quiere comprar un celular. Puede pagar de contado $900.000 o en 12 cuotas de $85.000. Si escoge cuotas, ¿cuanto terminaria pagando en total?",
    options: ["$85.000", "$900.000", "$985.000", "$1.020.000"],
    answer: 3,
    rationale: "12 x $85.000 = $1.020.000.",
    visual: {
      type: "installments",
      title: "Compra de celular",
      options: [
        { label: "Contado", value: "$900.000" },
        { label: "Cuotas", value: "12 x $85.000" },
      ],
    },
  },
  {
    id: 12,
    dimension: "credito-deuda",
    competence: "Evaluar alternativas",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt: "En el caso anterior, ¿que deberia comparar Laura antes de decidir?",
    options: [
      "Solo si la cuota mensual parece baja.",
      "El costo total que pagaria en cada opcion.",
      "Si sus amigos tienen el mismo celular.",
      "Si puede comprarlo sin leer las condiciones.",
    ],
    answer: 1,
    rationale: "La decision debe mirar costo total, no solo cuota mensual.",
    visual: {
      type: "installments",
      title: "Comparacion antes de decidir",
      options: [
        { label: "Contado", value: "$900.000" },
        { label: "Cuotas", value: "12 x $85.000" },
        { label: "Dato clave", value: "Costo total" },
      ],
    },
  },
  {
    id: 13,
    dimension: "credito-deuda",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Juan quiere comprar una bicicleta de $600.000. Le ofrecen pagarla en 6 cuotas de $110.000. ¿Cual afirmacion es correcta?",
    options: [
      "Pagara exactamente $600.000.",
      "Pagara menos que de contado.",
      "Pagara $660.000 en total.",
      "No se puede saber cuanto pagara.",
    ],
    answer: 2,
    rationale: "6 x $110.000 = $660.000.",
    visual: {
      type: "installments",
      title: "Bicicleta a cuotas",
      options: [
        { label: "Precio contado", value: "$600.000" },
        { label: "Plan de pago", value: "6 x $110.000" },
        { label: "Total", value: "?" },
      ],
    },
  },
  {
    id: 14,
    dimension: "credito-deuda",
    competence: "Evaluar riesgo",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Paula acepta prestar su nombre para que un amigo saque un producto a credito. El amigo promete pagar todas las cuotas. ¿Cual es el principal riesgo para Paula?",
    options: [
      "Que el producto sea muy bonito.",
      "Que si el amigo no paga, ella pueda quedar como responsable de la deuda.",
      "Que el producto llegue rapido.",
      "Que el credito desaparezca automaticamente.",
    ],
    answer: 1,
    rationale: "Quien figura en el credito puede asumir responsabilidad si no se paga.",
  },
  {
    id: 15,
    dimension: "credito-deuda",
    competence: "Proyectar compromiso futuro",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Samuel se suscribe a una aplicacion que cuesta $18.000 mensuales. Al principio piensa que es poco dinero. ¿Que deberia considerar antes de aceptar?",
    options: [
      "Solo el valor del primer mes.",
      "El costo acumulado durante varios meses y si podra pagarlo.",
      "Si la aplicacion tiene un logo llamativo.",
      "Si puede dejar de revisar sus gastos.",
    ],
    answer: 1,
    rationale: "Los pagos recurrentes comprometen dinero futuro.",
    visual: {
      type: "decision",
      title: "Pago recurrente",
      items: ["$18.000 cada mes", "No es un pago unico", "Compromete dinero futuro"],
    },
  },
  {
    id: 16,
    dimension: "riesgo-digital",
    competence: "Evaluar riesgo",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      'A Sebastian le escriben por Instagram diciendole que puede duplicar $50.000 en cinco dias. La persona le pide transferir rapido y no contarle a nadie porque "es una oportunidad exclusiva". ¿Cual seria la decision mas responsable?',
    options: [
      "Transferir rapido para no perder la oportunidad.",
      "Pedir prestado para invertir mas dinero.",
      "Desconfiar, no transferir y buscar informacion antes de tomar cualquier decision.",
      "Enviar el dinero si otros companeros tambien lo hacen.",
    ],
    answer: 2,
    rationale: "La rentabilidad rapida, urgencia y secreto son senales de riesgo.",
    visual: {
      type: "chat",
      title: "Mensaje por Instagram",
      messages: [
        "Invierte $50.000 hoy.",
        "En cinco dias recibes $100.000.",
        "No le cuentes a nadie. Es exclusivo.",
      ],
    },
  },
  {
    id: 17,
    dimension: "riesgo-digital",
    competence: "Evaluar riesgo",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt:
      'A Natalia le llega un mensaje que dice: "Ganaste un premio. Envianos tu clave o codigo de seguridad para reclamarlo". ¿Que deberia hacer?',
    options: [
      "Enviar la clave si el mensaje parece urgente.",
      "Enviar el codigo solo si el premio es grande.",
      "No compartir claves ni codigos y verificar por canales oficiales.",
      "Pedirle a un amigo que envie la clave por ella.",
    ],
    answer: 2,
    rationale: "Las claves y codigos de seguridad no deben compartirse.",
    visual: {
      type: "chat",
      title: "Mensaje sospechoso",
      messages: ["Ganaste un premio.", "Envia tu clave o codigo de seguridad para reclamarlo."],
    },
  },
  {
    id: 18,
    dimension: "riesgo-digital",
    competence: "Identificar senal de alerta",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "En un grupo de WhatsApp ofrecen una inversion que garantiza ganancias altas todas las semanas, pero no explican claramente como funciona. ¿Cual es una senal de alerta?",
    options: [
      "Que prometan ganancias garantizadas sin explicar el negocio.",
      "Que el mensaje tenga emojis.",
      "Que muchas personas esten en el grupo.",
      "Que se pueda pagar por transferencia.",
    ],
    answer: 0,
    rationale: "Una promesa garantizada sin explicacion clara debe verificarse.",
    visual: {
      type: "chat",
      title: "Grupo de WhatsApp",
      messages: ["Ganancias altas todas las semanas.", "No necesitas entender como funciona.", "Cupos limitados."],
    },
  },
  {
    id: 19,
    dimension: "riesgo-digital",
    competence: "Evaluar informacion antes de decidir",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      'Un companero insiste en que todos compren una rifa digital para "no quedar mal con el grupo", aunque nadie sabe quien organiza la rifa ni como se entrega el premio. ¿Que decision es mas responsable?',
    options: [
      "Comprar para evitar problemas con los amigos.",
      "Comprar varias para aumentar la posibilidad de ganar.",
      "Preguntar quien organiza, como se entrega el premio y decidir solo si la informacion es clara.",
      "Enviar dinero sin preguntar para terminar rapido.",
    ],
    answer: 2,
    rationale: "Una decision responsable verifica informacion antes de transferir dinero.",
    visual: {
      type: "chat",
      title: "Rifa digital",
      messages: ["Todos van a comprar.", "No quedes mal con el grupo.", "Envia rapido el dinero."],
    },
  },
  {
    id: 20,
    dimension: "riesgo-digital",
    competence: "Actitud / habito",
    type: "Actitudinal",
    difficulty: "No calificable",
    attitude: true,
    prompt: "Cuando veo en redes una forma rapida de ganar dinero, normalmente:",
    options: [
      "Me interesa y trato de entrar rapido antes de que se acabe.",
      "Reviso quien lo ofrece, que riesgos tiene y si la informacion es confiable.",
      "Lo comparto con amigos antes de entenderlo.",
      "Invierto poco dinero para probar suerte.",
    ],
    positive: 1,
    rationale: "La opcion B indica mayor criterio de verificacion.",
  },
  {
    id: 21,
    dimension: "trabajo-empresa",
    competence: "Aplicar conocimiento financiero",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Un grupo de estudiantes vende brownies en el colegio. Vendieron 40 brownies a $3.000 cada uno. Para prepararlos gastaron $75.000 en ingredientes y empaques. ¿Cual fue la ganancia del grupo?",
    options: ["$45.000", "$75.000", "$120.000", "$195.000"],
    answer: 0,
    rationale: "Ingresos: $120.000. Ganancia: $120.000 - $75.000 = $45.000.",
    visual: {
      type: "cashbook",
      title: "Venta de brownies",
      rows: [
        ["40 brownies x $3.000", "+$120.000"],
        ["Ingredientes y empaques", "-$75.000"],
        ["Ganancia", "?"],
      ],
    },
  },
  {
    id: 22,
    dimension: "trabajo-empresa",
    competence: "Interpretar ingresos y costos",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Un estudiante vendio 20 manillas a $5.000 cada una. Recibio $100.000 en total, pero gasto $60.000 en materiales. ¿Cual afirmacion es correcta?",
    options: [
      "Su ganancia fue $100.000.",
      "Su ganancia fue $60.000.",
      "Su ganancia fue $40.000.",
      "No tuvo ingresos.",
    ],
    answer: 2,
    rationale: "$100.000 - $60.000 = $40.000 de ganancia.",
    visual: {
      type: "cashbook",
      title: "Venta de manillas",
      rows: [
        ["Ingresos por ventas", "+$100.000"],
        ["Materiales", "-$60.000"],
        ["Ganancia", "?"],
      ],
    },
  },
  {
    id: 23,
    dimension: "trabajo-empresa",
    competence: "Aplicar registro de caja",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "En una caja habia $50.000 al iniciar el dia. Entraron $120.000 por ventas y salieron $35.000 para comprar materiales. ¿Cuanto dinero deberia haber al final?",
    options: ["$85.000", "$135.000", "$155.000", "$205.000"],
    answer: 1,
    rationale: "$50.000 + $120.000 - $35.000 = $135.000.",
    visual: {
      type: "cashbook",
      title: "Registro de caja",
      rows: [
        ["Caja inicial", "$50.000"],
        ["Ventas", "+$120.000"],
        ["Materiales", "-$35.000"],
        ["Saldo final", "?"],
      ],
    },
  },
  {
    id: 24,
    dimension: "trabajo-empresa",
    competence: "Analizar rentabilidad",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "Un grupo vendio muchos productos en una feria, pero al final descubrio que gasto casi lo mismo que recibio. ¿Que aprendizaje financiero deja esta situacion?",
    options: [
      "Vender mucho siempre significa ganar mucho.",
      "Lo importante es mirar ingresos, costos y ganancia, no solo ventas.",
      "Los costos no importan si hay muchas ventas.",
      "Siempre se gana cuando se vende algo.",
    ],
    answer: 1,
    rationale: "La rentabilidad depende de ingresos menos costos.",
  },
  {
    id: 25,
    dimension: "trabajo-empresa",
    competence: "Evaluar uso del ingreso",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Sara recibe $200.000 por ayudar en un negocio familiar durante vacaciones. Quiere gastar todo en ropa, pero tambien necesita guardar dinero para transporte del mes siguiente. ¿Cual decision muestra mejor manejo del ingreso?",
    options: [
      "Gastar todo en ropa porque el dinero es suyo.",
      "Separar primero transporte y una parte de ahorro, y luego decidir cuanto puede gastar.",
      "Prestar todo el dinero a una amiga sin acordar cuando se lo devuelve.",
      "Guardar el dinero sin revisar que obligaciones tiene.",
    ],
    answer: 1,
    rationale: "Primero cubre necesidad futura y ahorro antes del gasto opcional.",
  },
  {
    id: 26,
    dimension: "hogar-ciudadania",
    competence: "Identificar necesidad basica",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt:
      "En una familia hay que organizar el dinero del mes. ¿Cual de estos gastos normalmente deberia considerarse una necesidad basica?",
    options: [
      "Comprar un celular nuevo cada ano.",
      "Pagar alimentacion, transporte y servicios publicos.",
      "Comprar ropa de marca aunque no haga falta.",
      "Pagar una suscripcion que nadie usa.",
    ],
    answer: 1,
    rationale: "Alimentacion, transporte y servicios son necesidades basicas.",
    visual: {
      type: "budget",
      title: "Gastos del hogar",
      rows: [
        ["Alimentacion", "Necesidad"],
        ["Transporte", "Necesidad"],
        ["Servicios publicos", "Necesidad"],
        ["Compra opcional", "Deseo"],
      ],
    },
  },
  {
    id: 27,
    dimension: "hogar-ciudadania",
    competence: "Interpretar informacion del hogar",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "En una casa llego un recibo de energia mas alto que el mes anterior. ¿Cual seria una primera accion responsable?",
    options: [
      "Ignorar el recibo porque siempre llega igual.",
      "Revisar el consumo, la fecha de pago y posibles cambios en el uso de energia.",
      "No pagar nunca mas el servicio.",
      "Comprar mas electrodomesticos para aprovechar el pago.",
    ],
    answer: 1,
    rationale: "La primera accion es revisar consumo, fecha y cambios de uso.",
  },
  {
    id: 28,
    dimension: "hogar-ciudadania",
    competence: "Evaluar prioridades familiares",
    type: "Caso situacional",
    difficulty: "Media-alta",
    prompt:
      "En una familia hubo un gasto inesperado en salud. Ese mes el dinero no alcanza para pagar todo al mismo tiempo: energia, televisor en promocion, transporte al trabajo y parte de una deuda. ¿Cual opcion muestra mejor manejo de prioridades?",
    options: [
      "Comprar el televisor porque esta en promocion y despues resolver lo demas.",
      "Priorizar energia, transporte y deuda, y dejar la compra del televisor para otro momento.",
      "No pagar nada hasta tener todo el dinero completo.",
      "Usar el dinero de transporte para comprar el televisor y pedir ayuda despues.",
    ],
    answer: 1,
    rationale: "Prioriza necesidades, continuidad del ingreso y obligaciones.",
    visual: {
      type: "budget",
      title: "Mes con gasto inesperado",
      rows: [
        ["Energia", "Obligacion"],
        ["Transporte al trabajo", "Necesidad"],
        ["Deuda pendiente", "Compromiso"],
        ["Televisor en promocion", "Opcional"],
      ],
    },
  },
  {
    id: 29,
    dimension: "hogar-ciudadania",
    competence: "Evaluar consumo responsable",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "Un estudiante quiere ayudar a su familia a reducir gastos en casa. ¿Cual accion tiene mas relacion con consumo responsable?",
    options: [
      "Dejar luces y aparatos encendidos porque otros pagan.",
      "Revisar habitos de consumo de agua y energia, y evitar desperdicios.",
      "Comprar mas cosas en promocion aunque no se necesiten.",
      "No hablar nunca de dinero en familia.",
    ],
    answer: 1,
    rationale: "Reducir desperdicios ayuda al consumo responsable.",
  },
  {
    id: 30,
    dimension: "hogar-ciudadania",
    competence: "Evaluar decision compartida",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "En un grupo familiar todos quieren usar el dinero para cosas diferentes. Hay gastos obligatorios, una deuda pendiente y algunos deseos personales. ¿Que decision ayuda mas a manejar el dinero de forma responsable?",
    options: [
      "Que cada persona gaste sin contarle a los demas.",
      "Hacer una lista de prioridades y acordar que se paga primero.",
      "Usar todo en deseos personales para evitar discusiones.",
      "Pedir un prestamo sin revisar si podran pagarlo.",
    ],
    answer: 1,
    rationale: "Acordar prioridades ayuda a manejar recursos compartidos.",
    visual: {
      type: "decision",
      title: "Decision familiar",
      items: ["Gastos obligatorios", "Deuda pendiente", "Deseos personales", "Acuerdo de prioridades"],
    },
  },
];
