export const DIMENSIONS = [
  {
    id: "dinero-transacciones",
    name: "Consumo inteligente",
    shortName: "Consumo",
    pilot: "Piloto A: Bases financieras y transacciones cotidianas",
  },
  {
    id: "presupuesto-planificacion",
    name: "Presupuesto y prioridades",
    shortName: "Prioridades",
    pilot: "Piloto B: Planificacion, ahorro y decisiones de consumo",
  },
  {
    id: "credito-deuda",
    name: "Credito y costo real",
    shortName: "Credito",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "riesgo-digital",
    name: "Riesgo y fraude",
    shortName: "Fraude",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "trabajo-empresa",
    name: "Operacion y decisiones de negocio",
    shortName: "Operacion",
    pilot: "Piloto D: Emprendimiento, ingresos y manejo de caja",
  },
  {
    id: "hogar-ciudadania",
    name: "Economia aplicada y criterio",
    shortName: "Economia",
    pilot: "Piloto E: Hogar, ciudadania y responsabilidad economica",
  },
];

export const PILOTS = {
  bases: {
    id: "bases",
    name: "Piloto A: Bases financieras y transacciones cotidianas",
    focus: "Descuentos, condiciones de compra, costos adicionales y decisiones de consumo.",
    duration: "4 a 6 semanas",
  },
  planificacion: {
    id: "planificacion",
    name: "Piloto B: Planificacion, ahorro y decisiones de consumo",
    focus: "Prioridades, necesidades basicas, presupuesto y uso responsable del ingreso.",
    duration: "4 a 6 semanas",
  },
  creditoRiesgo: {
    id: "creditoRiesgo",
    name: "Piloto C: Credito, deuda y riesgo digital",
    focus: "Costo total, cuotas, verificacion, fraude y decisiones antes de transferir.",
    duration: "6 semanas",
  },
  empresa: {
    id: "empresa",
    name: "Piloto D: Emprendimiento, ingresos y manejo de caja",
    focus: "Caja, costos fijos y variables, registros operativos y lectura de decisiones de negocio.",
    duration: "4 a 6 semanas",
  },
  hogar: {
    id: "hogar",
    name: "Piloto E: Hogar, ciudadania y responsabilidad economica",
    focus: "Oferta y demanda, riqueza, decisiones complejas y criterio economico aplicado.",
    duration: "4 a 6 semanas",
  },
};

export const QUESTIONS = [
  {
    id: 1,
    dimension: "dinero-transacciones",
    competence: "Calcular descuento y vuelto",
    type: "Calculo aplicado",
    difficulty: "Basica",
    prompt: "Valeria compra alimentos por $16.500. Tiene 10% de descuento y paga con $20.000. ¿Cuanto recibe de vuelto?",
    options: ["$5.150", "$4.850", "$3.500", "$5.000"],
    answer: 0,
    rationale: "$16.500 con 10% de descuento equivale a $14.850. El vuelto es $5.150.",
    visual: {
      type: "receipt",
      title: "Compra con descuento",
      rows: [
        ["Compra", "$16.500"],
        ["Descuento", "10%"],
        ["Total a pagar", "$14.850"],
        ["Pago", "$20.000"],
      ],
    },
  },
  {
    id: 2,
    dimension: "dinero-transacciones",
    competence: "Reconocer condiciones de una promocion",
    type: "Lectura de promocion",
    difficulty: "Basica",
    prompt: "Una tienda anuncia 30% de descuento, pero solo aplica con una tarjeta especifica que el cliente no tiene. ¿Que precio paga realmente?",
    options: ["El precio con descuento", "La mitad del precio", "No puede comprar", "El precio original"],
    answer: 3,
    rationale: "Si no cumple la condicion del medio de pago, paga el precio original.",
    visual: {
      type: "receipt",
      title: "Promocion condicionada",
      rows: [
        ["Descuento", "30%"],
        ["Condicion", "Tarjeta especifica"],
        ["Sin tarjeta", "No aplica"],
      ],
    },
  },
  {
    id: 3,
    dimension: "dinero-transacciones",
    competence: "Identificar costos adicionales",
    type: "Lectura de compra",
    difficulty: "Basica",
    prompt: "Producto: $150.000. Envio: $12.000. Seguro obligatorio: $5.000. ¿Que representa el seguro?",
    options: ["Un impuesto", "Un costo adicional obligatorio", "Un descuento", "Un beneficio opcional"],
    answer: 1,
    rationale: "El seguro se presenta como un cobro adicional obligatorio dentro de la compra.",
    visual: {
      type: "receipt",
      title: "Compra en linea",
      rows: [
        ["Producto", "$150.000"],
        ["Envio", "$12.000"],
        ["Seguro", "$5.000"],
      ],
    },
  },
  {
    id: 4,
    dimension: "presupuesto-planificacion",
    competence: "Priorizar gastos obligatorios",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Un estudiante tiene $50.000 y debe pagar transporte ($18.000) y materiales ($12.000). Quiere comprar algo de $35.000. ¿Que deberia hacer primero?",
    options: ["Comprar lo que quiere", "Pedir dinero prestado", "No pagar sus obligaciones", "Cubrir sus gastos obligatorios"],
    answer: 3,
    rationale: "La prioridad es cubrir primero transporte y materiales.",
    visual: {
      type: "budget",
      title: "Presupuesto del estudiante",
      rows: [
        ["Disponible", "$50.000"],
        ["Transporte", "$18.000"],
        ["Materiales", "$12.000"],
        ["Deseo", "$35.000"],
      ],
    },
  },
  {
    id: 5,
    dimension: "presupuesto-planificacion",
    competence: "Ajustar otros gastos ante imprevistos",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Una familia enfrenta un gasto inesperado. ¿Cual es la decision mas responsable?",
    options: ["Ignorarlo", "Ajustar otros gastos", "Endeudarse sin plan", "No cubrir necesidades basicas"],
    answer: 1,
    rationale: "Primero se ajustan gastos para absorber el imprevisto antes de tomar decisiones mas riesgosas.",
  },
  {
    id: 6,
    dimension: "presupuesto-planificacion",
    competence: "Separar necesidades antes de gastar",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Sara recibe $200.000. Debe cubrir $80.000 en necesidades basicas. ¿Cual es la mejor decision?",
    options: ["Gastar todo", "Guardar sin plan", "Separar primero necesidades", "Prestar dinero"],
    answer: 2,
    rationale: "La mejor decision es separar primero las necesidades basicas.",
    visual: {
      type: "budget",
      title: "Ingreso de Sara",
      rows: [
        ["Ingreso", "$200.000"],
        ["Necesidades basicas", "$80.000"],
      ],
    },
  },
  {
    id: 7,
    dimension: "credito-deuda",
    competence: "Calcular costo total de un credito",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt: "Un producto se compra a 12 cuotas de $85.000 mas un seguro de $3.000 mensual. ¿Cuanto se paga en total?",
    options: ["$1.056.000", "$1.020.000", "$1.080.000", "$900.000"],
    answer: 0,
    rationale: "$88.000 por 12 meses da un total de $1.056.000.",
    visual: {
      type: "installments",
      title: "Credito con seguro",
      options: [
        { label: "Cuota", value: "$85.000" },
        { label: "Seguro", value: "$3.000" },
        { label: "Meses", value: "12" },
      ],
    },
  },
  {
    id: 8,
    dimension: "credito-deuda",
    competence: "Comparar creditos por costo total",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Para elegir correctamente un credito, lo mas importante es:",
    options: ["El valor de la cuota", "La popularidad del banco", "El plazo", "El costo total"],
    answer: 3,
    rationale: "El criterio correcto es revisar el costo total y no solo la cuota.",
    visual: {
      type: "installments",
      title: "Comparacion de credito",
      options: [
        { label: "Cuota", value: "No basta" },
        { label: "Costo total", value: "Clave" },
      ],
    },
  },
  {
    id: 9,
    dimension: "riesgo-digital",
    competence: "Detectar una oferta riesgosa",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Le ofrecen duplicar su dinero rapidamente sin explicar como. ¿Que deberia hacer?",
    options: ["Invertir", "Desconfiar", "Pedir dinero prestado", "Copiar a otros"],
    answer: 1,
    rationale: "Una promesa de duplicar dinero sin explicacion es una senal de alerta.",
    visual: {
      type: "chat",
      title: "Oferta sospechosa",
      messages: ["Duplica tu dinero rapido", "Sin explicacion clara"],
    },
  },
  {
    id: 10,
    dimension: "riesgo-digital",
    competence: "Proteger informacion bancaria",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Recibe un mensaje solicitando su clave bancaria. ¿Que debe hacer?",
    options: ["Enviarla", "Probar si funciona", "Verificar y no compartirla", "Compartirla con alguien cercano"],
    answer: 2,
    rationale: "La informacion bancaria no se comparte; se verifica por canales oficiales.",
    visual: {
      type: "chat",
      title: "Clave bancaria",
      messages: ["Envianos tu clave bancaria"],
    },
  },
  {
    id: 11,
    dimension: "riesgo-digital",
    competence: "Reconocer una promesa riesgosa",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: 'Una inversion promete "ganancias garantizadas". ¿Cual es la principal senal de alerta?',
    options: ["Uso de redes sociales", "Muchas personas participando", "Transferencia bancaria", "Promesa sin explicacion clara"],
    answer: 3,
    rationale: "La senal principal es prometer resultados garantizados sin explicar el negocio.",
    visual: {
      type: "chat",
      title: "Promesa de inversion",
      messages: ["Ganancias garantizadas", "Sin explicacion del negocio"],
    },
  },
  {
    id: 12,
    dimension: "trabajo-empresa",
    competence: "Reconstruir ventas desde movimientos de caja",
    type: "Calculo aplicado",
    difficulty: "Alta",
    prompt: "Un restaurante presenta: caja inicial $330.000, compras del dia $405.000, reposicion de efectivo $250.000 y caja final $875.000. ¿Cual fue el valor de las ventas?",
    options: ["$700.000", "$545.000", "$875.000", "$1.105.000"],
    answer: 0,
    rationale: "Ventas = caja final - caja inicial - reposicion + compras = $700.000.",
    visual: {
      type: "cashbook",
      title: "Operacion de restaurante",
      rows: [
        ["Caja inicial", "$330.000"],
        ["Compras", "-$405.000"],
        ["Reposicion", "+$250.000"],
        ["Caja final", "$875.000"],
      ],
    },
  },
  {
    id: 13,
    dimension: "trabajo-empresa",
    competence: "Identificar la naturaleza de una reposicion",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "¿Que representa la reposicion de efectivo?",
    options: ["Una venta", "Un ingreso operativo", "Una entrada de dinero externo", "Una ganancia"],
    answer: 2,
    rationale: "La reposicion es dinero externo que entra a caja, no una venta ni una ganancia.",
  },
  {
    id: 14,
    dimension: "trabajo-empresa",
    competence: "Reconocer un error de clasificacion",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Si el administrador registra la reposicion como venta, ¿que ocurre?",
    options: ["Subestima ingresos", "Sobreestima ingresos", "No afecta", "Reduce costos"],
    answer: 1,
    rationale: "Registrar la reposicion como venta infla artificialmente los ingresos.",
  },
  {
    id: 15,
    dimension: "trabajo-empresa",
    competence: "Distinguir costos fijos",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "En la compra de discos duros, si existe un costo de envio fijo, ¿que tipo de costo es el envio?",
    options: ["Variable", "Financiero", "Opcional", "Fijo"],
    answer: 3,
    rationale: "El envio fijo no cambia con la cantidad comprada.",
    visual: {
      type: "cashbook",
      title: "Compra de discos duros",
      rows: [
        ["Precio unitario", "$150.000"],
        ["Cantidad", "4 -> 2"],
        ["Envio", "Fijo"],
      ],
    },
  },
  {
    id: 16,
    dimension: "trabajo-empresa",
    competence: "Diferenciar costos variables de fijos",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "¿Que efecto tiene reducir la cantidad de discos duros de 4 a 2 unidades?",
    options: ["Reduce solo los costos variables", "Reduce proporcionalmente el total", "Elimina el envio", "Reduce impuestos a cero"],
    answer: 0,
    rationale: "Reducir la cantidad baja el costo variable, pero no necesariamente el costo fijo.",
  },
  {
    id: 17,
    dimension: "trabajo-empresa",
    competence: "Reconocer un error de analisis",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "¿Cual error podria cometer el administrador?",
    options: ["Calcular impuestos", "Ignorar costos fijos", "Comparar precios", "Reducir compras"],
    answer: 1,
    rationale: "Un error comun es ignorar costos fijos al evaluar una compra.",
  },
  {
    id: 18,
    dimension: "hogar-ciudadania",
    competence: "Relacionar oferta, demanda y precio",
    type: "Conceptual aplicada",
    difficulty: "Basica",
    prompt: "Si la demanda aumenta y la oferta es baja:",
    options: ["El precio baja", "No cambia", "El precio sube", "Desaparece"],
    answer: 2,
    rationale: "Con mayor demanda y menor oferta, el precio tiende a subir.",
  },
  {
    id: 19,
    dimension: "hogar-ciudadania",
    competence: "Definir riqueza",
    type: "Conceptual aplicada",
    difficulty: "Basica",
    prompt: "La riqueza se define como:",
    options: ["Dinero disponible", "Ingresos", "Valor de los activos", "Gastos"],
    answer: 2,
    rationale: "La riqueza se mide mejor por el valor de los activos.",
  },
  {
    id: 20,
    dimension: "hogar-ciudadania",
    competence: "Reconocer riesgo por deterioro",
    type: "Juicio situacional",
    difficulty: "Basica",
    prompt: "Comprar productos mas baratos en grandes cantidades puede generar:",
    options: ["Perdidas por deterioro", "Ahorro seguro", "Mas ventas", "Menor riesgo"],
    answer: 0,
    rationale: "Comprar por volumen puede traer perdidas si los productos se deterioran.",
  },
];
