export const DIMENSIONS = [
  {
    id: "dinero-transacciones",
    name: "Dinero y transacciones",
    shortName: "Transacciones",
    pilot: "Piloto A: Bases financieras y transacciones cotidianas",
  },
  {
    id: "presupuesto-planificacion",
    name: "Presupuesto y planificacion",
    shortName: "Planificacion",
    pilot: "Piloto B: Planificacion, ahorro y decisiones de consumo",
  },
  {
    id: "credito-deuda",
    name: "Credito, deuda y costo del dinero",
    shortName: "Credito y deuda",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "riesgo-digital",
    name: "Riesgo, fraude y decisiones digitales",
    shortName: "Riesgo digital",
    pilot: "Piloto C: Credito, deuda y riesgo digital",
  },
  {
    id: "trabajo-empresa",
    name: "Trabajo, empresa e ingresos",
    shortName: "Empresa e ingresos",
    pilot: "Piloto D: Emprendimiento, ingresos y manejo de caja",
  },
  {
    id: "hogar-ciudadania",
    name: "Hogar, ciudadania y responsabilidad economica",
    shortName: "Hogar y ciudadania",
    pilot: "Piloto E: Hogar, ciudadania y responsabilidad economica",
  },
];

export const PILOTS = {
  bases: {
    id: "bases",
    name: "Piloto A: Bases financieras y transacciones cotidianas",
    focus: "Compras, pagos, descuentos, recibos, comprobantes y costo total.",
    duration: "4 a 6 semanas",
  },
  planificacion: {
    id: "planificacion",
    name: "Piloto B: Planificacion, ahorro y decisiones de consumo",
    focus: "Presupuesto, ahorro, priorizacion, manejo de dinero limitado y consumo.",
    duration: "6 semanas",
  },
  creditoRiesgo: {
    id: "creditoRiesgo",
    name: "Piloto C: Credito, deuda y riesgo digital",
    focus: "Costo total, cuotas, compromisos futuros, fraude digital y verificacion.",
    duration: "6 semanas",
  },
  empresa: {
    id: "empresa",
    name: "Piloto D: Emprendimiento, ingresos y manejo de caja",
    focus: "Ingresos, costos, utilidad, caja y emprendimiento escolar.",
    duration: "4 a 6 semanas",
  },
  hogar: {
    id: "hogar",
    name: "Piloto E: Hogar, ciudadania y responsabilidad economica",
    focus: "Presupuesto familiar, consumo responsable, decisiones compartidas y prioridades.",
    duration: "4 a 6 semanas",
  },
};

export const QUESTIONS = [
  {
    id: 1,
    dimension: "dinero-transacciones",
    competence: "Calcular descuento, vuelto y proporcion del presupuesto",
    type: "Calculo aplicado",
    difficulty: "Media-alta",
    prompt:
      "Valeria tiene un presupuesto semanal de $60.000 para comida. Hoy compra: sandwich $8.500, jugo $4.200 y ensalada $3.800. En la tienda hay dos promociones: Promo A, 10% de descuento en compras mayores a $15.000; Promo B, segundo jugo a mitad de precio, solo si lleva 2 jugos. Valeria elige la Promo A y paga con $20.000. ¿Cuanto vuelto recibe y que porcentaje de su presupuesto semanal ha gastado?",
    options: [
      "Vuelto $5.150; gasto el 24,75% del presupuesto semanal.",
      "Vuelto $4.850; gasto el 26,7% del presupuesto semanal.",
      "Vuelto $5.150; gasto el 27,5% porque calculo mal el descuento.",
      "Vuelto $4.200; gasto el 28% porque aplico la Promo B por error.",
    ],
    answer: 0,
    rationale: "La compra suma $16.500. Con 10% de descuento paga $14.850, recibe $5.150 y usa 24,75% de $60.000.",
    visual: {
      type: "receipt",
      title: "Compra con promocion",
      rows: [
        ["Sandwich", "$8.500"],
        ["Jugo", "$4.200"],
        ["Ensalada", "$3.800"],
        ["Promo A", "10%"],
        ["Pago", "$20.000"],
      ],
    },
  },
  {
    id: 2,
    dimension: "dinero-transacciones",
    competence: "Identificar condiciones de una promocion",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      'Una tienda anuncia: "Camiseta: precio original $80.000, 25% de descuento". Pero al llegar a la caja, te dicen que el descuento es solo si pagas con tarjeta de credito de un banco especifico, y tu no tienes esa tarjeta. ¿Cual es el precio que realmente pagarias?',
    options: ["$20.000", "$55.000", "$60.000", "$80.000"],
    answer: 3,
    rationale: "El descuento condicionado no aplica si no se cumple la condicion de pago.",
    visual: {
      type: "receipt",
      title: "Promocion condicionada",
      rows: [
        ["Precio original", "$80.000"],
        ["Descuento", "25%"],
        ["Condicion", "Tarjeta especifica"],
      ],
    },
  },
  {
    id: 3,
    dimension: "dinero-transacciones",
    competence: "Calcular costo total con cargos adicionales",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Daniel compra unos tenis de $150.000 en una pagina web. El sitio muestra un costo de envio de $12.000, pero en el ultimo paso agrega un seguro de envio obligatorio de $5.000 que no estaba visible antes. ¿Cual es el costo total final?",
    options: ["$138.000", "$150.000", "$167.000", "$152.000"],
    answer: 2,
    rationale: "$150.000 + $12.000 + $5.000 = $167.000.",
    visual: {
      type: "receipt",
      title: "Compra en linea",
      rows: [
        ["Tenis", "$150.000"],
        ["Envio", "$12.000"],
        ["Seguro obligatorio", "$5.000"],
        ["Total", "?"],
      ],
    },
  },
  {
    id: 4,
    dimension: "dinero-transacciones",
    competence: "Comparar medios de pago y comisiones",
    type: "Interpretacion de recibo",
    difficulty: "Media",
    prompt:
      "Sofia compra: cuaderno $9.000, lapices $6.000 y cartulina $3.500. Tiene dos opciones de pago: Opcion 1, pagar con $20.000 en efectivo y recibir vuelto; Opcion 2, pagar con tarjeta debito que le cobra una comision de $500 por transaccion. ¿Cual opcion es financieramente mejor y por que?",
    options: [
      "Opcion 1, porque el vuelto es $1.500 y no paga comision.",
      "Opcion 2, porque es mas moderna y rapida.",
      "Opcion 1, porque el vuelto es $2.500.",
      "Opcion 2, porque la comision es muy baja.",
    ],
    answer: 0,
    rationale: "$9.000 + $6.000 + $3.500 = $18.500. En efectivo recibe $1.500 y no paga comision.",
    visual: {
      type: "receipt",
      title: "Recibo de papeleria",
      rows: [
        ["Cuaderno", "$9.000"],
        ["Lapices", "$6.000"],
        ["Cartulina", "$3.500"],
        ["Comision debito", "$500"],
      ],
    },
  },
  {
    id: 5,
    dimension: "dinero-transacciones",
    competence: "Evaluar respaldo de comprobantes y mediacion",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Maria compra un telefono usado por $350.000 en una plataforma de ventas entre particulares. El vendedor le ofrece dos opciones: Opcion A, transferencia bancaria directa sin comision y comprobante por WhatsApp; Opcion B, pago a traves de la plataforma con comision de $10.000, pero la plataforma retiene el dinero hasta que Maria confirme que el producto funciona. Maria elige la Opcion A. Al recibir el telefono, descubre que no enciende. El vendedor ya no responde. ¿Cual es el valor real del comprobante de pago que recibio?",
    options: [
      "Alto, porque puede presentarlo ante la plataforma para que le devuelvan el dinero.",
      "Nulo, porque no tiene mediacion ni mecanismo efectivo de reclamo.",
      "Medio, porque puede demandar al vendedor en un proceso judicial sencillo.",
      "Depende de si guardo la conversacion de WhatsApp; si es asi, puede recuperar el dinero.",
    ],
    answer: 1,
    rationale: "Sin mediacion, el comprobante prueba un pago, pero no activa por si solo un mecanismo efectivo de reclamo.",
    visual: {
      type: "decision",
      title: "Compra entre particulares",
      items: ["Transferencia directa", "Comprobante por WhatsApp", "Sin retencion de dinero", "Sin mediacion efectiva"],
    },
  },
  {
    id: 6,
    dimension: "presupuesto-planificacion",
    competence: "Recalcular una meta de ahorro ante imprevistos",
    type: "Calculo aplicado",
    difficulty: "Media-alta",
    prompt:
      "Mariana quiere ahorrar $120.000 en 6 semanas para una actividad del colegio. Planeaba ahorrar $20.000 cada semana. En la semana 3, tiene un gasto medico inesperado de $15.000 que reduce su capacidad de ahorro, y solo puede ahorrar $5.000 esa semana. ¿Cuanto deberia ahorrar en las semanas restantes 4, 5 y 6 para alcanzar la meta?",
    options: ["$20.000 semanales", "$22.500 semanales", "$25.000 semanales", "$27.500 semanales"],
    answer: 2,
    rationale: "Ahorro $20.000 + $20.000 + $5.000 = $45.000. Faltan $75.000 en 3 semanas: $25.000 por semana.",
    visual: {
      type: "budget",
      title: "Meta de ahorro",
      rows: [
        ["Meta", "$120.000"],
        ["Ahorrado semanas 1 y 2", "$40.000"],
        ["Semana 3", "$5.000"],
        ["Faltante", "$75.000"],
      ],
    },
  },
  {
    id: 7,
    dimension: "presupuesto-planificacion",
    competence: "Priorizar obligaciones antes de deseos",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Camila tiene $50.000. Debe pagar $18.000 de transporte y $12.000 de materiales. Quiere comprar una gorra de $35.000. ¿Que deberia hacer primero?",
    options: [
      "Comprar la gorra porque es lo que mas quiere.",
      "Gastar todo y pedir prestado para los materiales.",
      "No pagar transporte ni materiales para ahorrar.",
      "Separar transporte y materiales antes de decidir si compra la gorra.",
    ],
    answer: 3,
    rationale: "Primero se cubren transporte y materiales; despues se revisa si el gasto opcional es viable.",
    visual: {
      type: "budget",
      title: "Prioridades de Camila",
      rows: [
        ["Disponible", "$50.000"],
        ["Transporte", "$18.000"],
        ["Materiales", "$12.000"],
        ["Gorra", "$35.000"],
      ],
    },
  },
  {
    id: 8,
    dimension: "presupuesto-planificacion",
    competence: "Ajustar presupuesto ante imprevistos",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "Una familia planeo gastar $300.000 en mercado, pero ese mes tuvo que pagar $80.000 adicionales por un arreglo urgente. ¿Cual es la decision mas responsable?",
    options: [
      "Ignorar el gasto urgente y seguir gastando igual.",
      "Revisar el presupuesto y ajustar algunos gastos no necesarios.",
      "Pedir prestado sin saber como pagara.",
      "Dejar de comprar alimentos para cubrir todo el arreglo.",
    ],
    answer: 1,
    rationale: "Un imprevisto exige ajustar gastos discrecionales sin descuidar necesidades basicas.",
  },
  {
    id: 9,
    dimension: "presupuesto-planificacion",
    competence: "Reconocer habitos de planificacion",
    type: "Habito financiero",
    difficulty: "Basica",
    prompt: "Cuando quiero comprar algo y no me alcanza el dinero, normalmente:",
    options: [
      "Reviso si puedo esperar, ahorrar o buscar una opcion mas economica.",
      "Lo compro igual si puedo pedir prestado.",
      "Le pido dinero a alguien sin pensar mucho.",
      "Uso el dinero que tenia separado para algo importante.",
    ],
    answer: 0,
    rationale: "La respuesta responsable muestra espera, ahorro y busqueda de alternativas.",
  },
  {
    id: 10,
    dimension: "presupuesto-planificacion",
    competence: "Separar necesidades, ahorro y gasto disponible",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Sara recibe $200.000 por ayudar en un negocio familiar. Quiere gastar todo en ropa, pero tambien necesita $50.000 para transporte del mes siguiente y quiere ahorrar $30.000 para un curso. ¿Que decision muestra mejor manejo del ingreso?",
    options: [
      "Gastar todo en ropa porque el dinero es suyo.",
      "Prestar todo a una amiga sin acordar cuando le devuelve.",
      "Separar primero transporte y ahorro, y luego decidir cuanto puede gastar en ropa.",
      "Guardar el dinero sin revisar sus obligaciones.",
    ],
    answer: 2,
    rationale: "Se separan $50.000 de transporte y $30.000 de ahorro antes de decidir sobre el gasto en ropa.",
    visual: {
      type: "budget",
      title: "Ingreso de Sara",
      rows: [
        ["Ingreso", "$200.000"],
        ["Transporte", "$50.000"],
        ["Ahorro curso", "$30.000"],
        ["Disponible para ropa", "$120.000"],
      ],
    },
  },
  {
    id: 11,
    dimension: "credito-deuda",
    competence: "Calcular costo total de cuotas con cargos incluidos",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Laura quiere comprar un celular. Puede pagar de contado $900.000 o en 12 cuotas de $85.000. Ademas, la tarjeta cobra un seguro de vida de $3.000 mensual incluido en la cuota. ¿Cuanto terminaria pagando en total con el plan de cuotas?",
    options: ["$1.020.000", "$1.056.000", "$1.080.000", "$900.000"],
    answer: 1,
    rationale: "Cada mes paga $85.000 + $3.000 = $88.000. En 12 meses paga $1.056.000.",
    visual: {
      type: "installments",
      title: "Celular a cuotas",
      options: [
        { label: "Cuota base", value: "$85.000" },
        { label: "Seguro mensual", value: "$3.000" },
        { label: "Plazo", value: "12 meses" },
      ],
    },
  },
  {
    id: 12,
    dimension: "credito-deuda",
    competence: "Comparar costo total y condiciones de financiacion",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Laura tiene dos opciones de financiacion para el celular: Plan X, 6 cuotas sin interes, pero con cargo de administracion unico de $25.000; Plan Y, 12 cuotas con 2,5% de interes mensual sobre saldo deudor. Laura planea pagar el total en 6 meses aunque elija el Plan Y, haciendo pagos anticipados sin penalizacion. ¿Que deberia comparar para decidir correctamente?",
    options: [
      "Solo el monto de la cuota mensual.",
      "La tasa de interes efectiva anual, porque los cargos administrativos son equivalentes a intereses.",
      "Si sus amigos tienen el mismo celular.",
      "El costo total de cada plan, incluyendo si hay penalizacion por prepago.",
    ],
    answer: 3,
    rationale: "La comparacion debe incluir costo total, cargos y condiciones de prepago.",
    visual: {
      type: "installments",
      title: "Comparacion de financiacion",
      options: [
        { label: "Plan X", value: "Cargo unico $25.000" },
        { label: "Plan Y", value: "2,5% mensual" },
        { label: "Dato clave", value: "Costo total" },
      ],
    },
  },
  {
    id: 13,
    dimension: "credito-deuda",
    competence: "Calcular costo total de cuotas",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt: "Juan compra una bicicleta de $600.000 en 6 cuotas de $110.000. ¿Cual afirmacion es correcta?",
    options: [
      "Pagara exactamente $600.000.",
      "Pagara menos que de contado.",
      "Pagara $660.000 en total.",
      "No se puede saber porque depende de la inflacion.",
    ],
    answer: 2,
    rationale: "6 cuotas de $110.000 suman $660.000.",
    visual: {
      type: "installments",
      title: "Bicicleta a cuotas",
      options: [
        { label: "Precio contado", value: "$600.000" },
        { label: "Plan de pago", value: "6 x $110.000" },
        { label: "Total", value: "?" },
      ],
    },
  },
  {
    id: 14,
    dimension: "credito-deuda",
    competence: "Reconocer responsabilidad de codeudor",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Paula acepta prestar su nombre para que un amigo saque un producto a credito, actuando como codeudora. El amigo promete pagar todas las cuotas. ¿Cual es el principal riesgo para Paula?",
    options: [
      "Que si el amigo no paga, ella queda como responsable de la deuda ante el banco.",
      "Que el producto sea muy bonito.",
      "Que el producto llegue rapido.",
      "Que el credito desaparezca automaticamente.",
    ],
    answer: 0,
    rationale: "El codeudor asume responsabilidad solidaria si el titular no paga.",
  },
  {
    id: 15,
    dimension: "credito-deuda",
    competence: "Proyectar pagos recurrentes",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "Samuel se suscribe a una app que cuesta $18.000 mensuales. Al principio piensa que es poco. ¿Que deberia considerar antes de aceptar?",
    options: [
      "Solo el valor del primer mes.",
      "Si la aplicacion tiene un logo llamativo.",
      "Si puede dejar de revisar sus gastos.",
      "El costo acumulado durante varios meses y si podra pagarlo junto con sus otros gastos.",
    ],
    answer: 3,
    rationale: "Las suscripciones comprometen dinero futuro y deben evaluarse junto con otros gastos.",
    visual: {
      type: "decision",
      title: "Pago recurrente",
      items: ["$18.000 cada mes", "No es un pago unico", "Compromete dinero futuro"],
    },
  },
  {
    id: 16,
    dimension: "riesgo-digital",
    competence: "Detectar senales de estafa digital",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "A Sebastian le escriben por Instagram diciendole que puede duplicar $50.000 en cinco dias. La persona le pide transferir rapido y no contarle a nadie porque es una oportunidad exclusiva. Sebastian investiga y descubre que la cuenta tiene solo 3 dias de antiguedad y no hay informacion de la empresa. ¿Cual es la decision mas responsable?",
    options: [
      "Transferir rapido para no perder la oportunidad.",
      "Pedir prestado para invertir mas dinero.",
      "Desconfiar, no transferir y reportar la cuenta como estafa.",
      "Enviar el dinero si otros companeros tambien lo hacen.",
    ],
    answer: 2,
    rationale: "Promesa irreal, urgencia, secreto y cuenta nueva son senales de estafa.",
    visual: {
      type: "chat",
      title: "Mensaje por Instagram",
      messages: ["Duplica $50.000 en cinco dias.", "No le cuentes a nadie.", "Cuenta creada hace 3 dias."],
    },
  },
  {
    id: 17,
    dimension: "riesgo-digital",
    competence: "Prevenir phishing y robo de claves",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "A Natalia le llega un mensaje que dice: Ganaste un premio. Envianos tu clave o codigo de seguridad para reclamarlo. El mensaje incluye el logo de su banco, pero la direccion de correo es extrana. ¿Que deberia hacer?",
    options: [
      "No compartir claves ni codigos, y verificar directamente con el banco a traves de sus canales oficiales.",
      "Enviar la clave si el mensaje parece urgente.",
      "Enviar el codigo solo si el premio es grande.",
      "Pedirle a un amigo que envie la clave por ella.",
    ],
    answer: 0,
    rationale: "En phishing no se comparten claves ni codigos; se verifica por canales oficiales.",
    visual: {
      type: "chat",
      title: "Mensaje sospechoso",
      messages: ["Ganaste un premio.", "Envia tu clave.", "Correo de origen extrano."],
    },
  },
  {
    id: 18,
    dimension: "riesgo-digital",
    competence: "Identificar senales de alerta en inversiones",
    type: "Caso situacional",
    difficulty: "Media",
    prompt:
      "En un grupo de WhatsApp ofrecen una inversion que garantiza ganancias altas todas las semanas, pero no explican claramente como funciona ni quien esta detras. ¿Cual es la senal de alerta mas importante?",
    options: [
      "Que el mensaje tenga emojis.",
      "Que muchas personas esten en el grupo.",
      "Que se pueda pagar por transferencia.",
      "Que prometan ganancias garantizadas sin explicar el negocio.",
    ],
    answer: 3,
    rationale: "Garantizar ganancias sin explicar el negocio es una alerta central.",
    visual: {
      type: "chat",
      title: "Grupo de WhatsApp",
      messages: ["Ganancias altas todas las semanas.", "No necesitas entender como funciona.", "Cupos limitados."],
    },
  },
  {
    id: 19,
    dimension: "riesgo-digital",
    competence: "Resistir presion social y verificar informacion",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "Un companero insiste en que todos compren una rifa digital para no quedar mal con el grupo, aunque nadie sabe quien organiza la rifa ni como se entrega el premio. ¿Que decision es mas responsable?",
    options: [
      "Comprar para evitar problemas con los amigos.",
      "Preguntar quien organiza, como se entrega el premio y decidir solo si la informacion es clara.",
      "Comprar varias para aumentar la posibilidad de ganar.",
      "Enviar dinero sin preguntar para terminar rapido.",
    ],
    answer: 1,
    rationale: "La decision responsable verifica informacion antes de transferir dinero y no cede solo a presion social.",
    visual: {
      type: "chat",
      title: "Rifa digital",
      messages: ["Todos van a comprar.", "No quedes mal con el grupo.", "No hay informacion clara."],
    },
  },
  {
    id: 20,
    dimension: "riesgo-digital",
    competence: "Aplicar criterio critico ante oportunidades en redes",
    type: "Habito financiero",
    difficulty: "Basica",
    prompt: "Cuando veo en redes una forma rapida de ganar dinero, normalmente:",
    options: [
      "Me intereso y trato de entrar rapido antes de que se acabe.",
      "Lo comparto con amigos antes de entenderlo.",
      "Reviso quien lo ofrece, que riesgos tiene y si la informacion es confiable.",
      "Invierto poco dinero para probar suerte.",
    ],
    answer: 2,
    rationale: "La respuesta responsable muestra criterio de verificacion ante oportunidades rapidas.",
  },
  {
    id: 21,
    dimension: "trabajo-empresa",
    competence: "Reconstruir ventas a partir de movimientos de caja",
    type: "Calculo aplicado",
    difficulty: "Alta",
    prompt:
      "Un restaurante abre a las 10:00 am con $330.000 en caja. A las 10:30 compra $280.000 en bebidas y $30.000 en elementos de cocina. A las 11:00 am el administrador hace una reposicion de efectivo de $250.000. A las 3:00 pm se compran vasos y platos por $95.000. A las 9:00 pm el restaurante cierra con una caja final de $875.000. ¿Cual fue el total de ventas del dia?",
    options: ["$700.000", "$875.000", "$1.200.000", "$1.000.000"],
    answer: 0,
    rationale: "Ventas = caja final - caja inicial - reposicion + compras: $875.000 - $330.000 - $250.000 + $405.000 = $700.000.",
    visual: {
      type: "cashbook",
      title: "Caja del restaurante",
      rows: [
        ["Caja inicial", "$330.000"],
        ["Compras", "-$405.000"],
        ["Reposicion", "+$250.000"],
        ["Caja final", "$875.000"],
      ],
    },
  },
  {
    id: 22,
    dimension: "trabajo-empresa",
    competence: "Calcular ganancia neta",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Un grupo de estudiantes vende brownies. Vendieron 40 brownies a $3.000 cada uno. Gastaron $75.000 en ingredientes y empaques. Ademas, tuvieron que pagar $10.000 por el alquiler de un puesto en la feria. ¿Cual fue la ganancia neta?",
    options: ["$45.000", "$35.000", "$120.000", "$195.000"],
    answer: 1,
    rationale: "Ingresos $120.000 menos costos $75.000 + $10.000 = $35.000.",
    visual: {
      type: "cashbook",
      title: "Venta de brownies",
      rows: [
        ["Ingresos", "+$120.000"],
        ["Ingredientes y empaques", "-$75.000"],
        ["Alquiler puesto", "-$10.000"],
        ["Ganancia neta", "?"],
      ],
    },
  },
  {
    id: 23,
    dimension: "trabajo-empresa",
    competence: "Distinguir ingresos, costos y ganancia",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "Un estudiante vendio 20 manillas a $5.000 cada una. Recibio $100.000 en total, pero gasto $60.000 en materiales y $15.000 en el transporte para ir a vender. ¿Cual afirmacion es correcta?",
    options: [
      "Su ganancia fue $100.000.",
      "Su ganancia fue $60.000.",
      "Su ganancia fue $25.000.",
      "Su ganancia fue $40.000.",
    ],
    answer: 2,
    rationale: "Ingresos $100.000 menos costos $60.000 + $15.000 = $25.000.",
    visual: {
      type: "cashbook",
      title: "Venta de manillas",
      rows: [
        ["Ingresos por ventas", "+$100.000"],
        ["Materiales", "-$60.000"],
        ["Transporte", "-$15.000"],
        ["Ganancia", "?"],
      ],
    },
  },
  {
    id: 24,
    dimension: "trabajo-empresa",
    competence: "Actualizar saldo de caja con entradas y salidas",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt:
      "En una caja habia $50.000 al iniciar el dia. Entraron $120.000 por ventas y salieron $35.000 para comprar materiales. Ademas, se retiraron $20.000 para pagar un pequeno prestamo. ¿Cuanto dinero deberia haber al final?",
    options: ["$85.000", "$135.000", "$155.000", "$115.000"],
    answer: 3,
    rationale: "$50.000 + $120.000 - $35.000 - $20.000 = $115.000.",
    visual: {
      type: "cashbook",
      title: "Registro de caja",
      rows: [
        ["Caja inicial", "$50.000"],
        ["Ventas", "+$120.000"],
        ["Materiales", "-$35.000"],
        ["Prestamo", "-$20.000"],
      ],
    },
  },
  {
    id: 25,
    dimension: "trabajo-empresa",
    competence: "Recalcular factura con cambio de cantidad",
    type: "Calculo aplicado",
    difficulty: "Alta",
    prompt:
      "De acuerdo con una factura con teclado 3 x $60.000, mouse 4 x $15.000, impresora 2 x $410.000, disco duro 4 x $150.000 y monitor 2 x $350.000, si en lugar de 4 discos duros se hubieran facturado 2, y todo lo demas queda igual, ¿cual seria el nuevo total final si el subtotal ajustado recibe 10% de impuestos y $150.000 de envio?",
    options: ["$2.416.000", "$2.360.000", "$2.546.000", "$2.200.000"],
    answer: 0,
    rationale: "Nuevo subtotal: $2.060.000. Impuestos 10%: $206.000. Envio: $150.000. Total: $2.416.000.",
    visual: {
      type: "cashbook",
      title: "Factura ajustada",
      rows: [
        ["Subtotal ajustado", "$2.060.000"],
        ["Impuestos 10%", "+$206.000"],
        ["Envio", "+$150.000"],
        ["Total final", "?"],
      ],
    },
  },
  {
    id: 26,
    dimension: "hogar-ciudadania",
    competence: "Relacionar ventas, costos y rentabilidad",
    type: "Juicio situacional",
    difficulty: "Media",
    prompt:
      "Un grupo vendio muchos productos en una feria, pero al final descubrio que gasto casi lo mismo que recibio. ¿Que aprendizaje financiero deja esta situacion?",
    options: [
      "Vender mucho siempre significa ganar mucho.",
      "Lo importante es mirar ingresos, costos y ganancia, no solo ventas.",
      "Los costos no importan si hay muchas ventas.",
      "Siempre se gana cuando se vende algo.",
    ],
    answer: 1,
    rationale: "La rentabilidad depende de ingresos menos costos, no solo del volumen de ventas.",
  },
  {
    id: 27,
    dimension: "hogar-ciudadania",
    competence: "Interpretar efecto de tasa de cambio",
    type: "Calculo aplicado",
    difficulty: "Alta",
    prompt:
      "Un exportador frances vende a Estados Unidos 3.000 botellas de vino a 18 euros cada una. Factura en dolares pagaderos en 90 dias. Hoy el dolar cotiza a 0,90 euros. En 90 dias la tasa es 0,96 euros por dolar. ¿Cual es la diferencia en euros entre lo que recibiria si facturara hoy en euros y lo que realmente recibe al facturar en dolares?",
    options: ["3.600 euros en contra del exportador.", "54.000 euros en contra.", "3.600 euros a favor del exportador.", "No hay diferencia."],
    answer: 2,
    rationale: "La venta equivale a 60.000 USD. A 0,96 recibe 57.600 euros frente a 54.000 euros facturados hoy: diferencia de 3.600 euros a favor.",
    visual: {
      type: "decision",
      title: "Venta internacional",
      items: ["3.000 botellas", "18 euros c/u", "60.000 USD", "Tasa sube de 0,90 a 0,96"],
    },
  },
  {
    id: 28,
    dimension: "hogar-ciudadania",
    competence: "Calcular precios antes de impuestos",
    type: "Calculo aplicado",
    difficulty: "Alta",
    prompt:
      "Los siguientes precios ya incluyen un impuesto del 16%: gafas $174.000, perfume $162.400, reloj $40.600, collar y aretes $75.400. Calcula el precio antes de impuestos de cada producto y luego el subtotal total antes de impuestos. ¿Cual es el subtotal antes de impuestos?",
    options: ["$380.000", "$400.000", "$410.000", "$390.000"],
    answer: 3,
    rationale: "Cada precio se divide entre 1,16: $150.000 + $140.000 + $35.000 + $65.000 = $390.000.",
    visual: {
      type: "receipt",
      title: "Precios con impuesto incluido",
      rows: [
        ["Gafas", "$174.000"],
        ["Perfume", "$162.400"],
        ["Reloj", "$40.600"],
        ["Collar y aretes", "$75.400"],
      ],
    },
  },
  {
    id: 29,
    dimension: "hogar-ciudadania",
    competence: "Evaluar compra eficiente segun consumo y desperdicio",
    type: "Juicio situacional",
    difficulty: "Alta",
    prompt:
      "Un kilo de tomates cuesta $3.000. Una caja de 10 kilos cuesta $25.000. Cada kilo trae en promedio 6 tomates. Cada tomate dura 4 dias antes de danarse. Un restaurante consume 10 tomates diarios. ¿Cual es la opcion mas razonable para ahorrar?",
    options: [
      "Comprar una caja cada 6 dias.",
      "Comprar 1 kilo diario.",
      "Comprar 2 kilos diarios.",
      "Comprar 2 kilos diarios y al tercer dia solo 1 kilo.",
    ],
    answer: 0,
    rationale: "Una caja trae cerca de 60 tomates, cubre 6 dias de consumo y cuesta menos que comprar por kilo.",
    visual: {
      type: "budget",
      title: "Compra de tomates",
      rows: [
        ["Kilo", "$3.000"],
        ["Caja 10 kg", "$25.000"],
        ["Tomates por kilo", "6"],
        ["Consumo diario", "10"],
      ],
    },
  },
  {
    id: 30,
    dimension: "hogar-ciudadania",
    competence: "Calcular costo unitario por consumo",
    type: "Calculo aplicado",
    difficulty: "Media",
    prompt: "Al comprar el tomate por kilo, no por caja, ¿cuanto costaria comprar 60 tomates?",
    options: ["$25.000", "$30.000", "$35.000", "$40.000"],
    answer: 1,
    rationale: "60 tomates equivalen a 10 kilos. A $3.000 por kilo, el costo es $30.000.",
    visual: {
      type: "budget",
      title: "Tomates por kilo",
      rows: [
        ["60 tomates", "10 kilos"],
        ["Precio por kilo", "$3.000"],
        ["Total", "?"],
      ],
    },
  },
];
